language: node_js
sudo: false

node_js:
  - '6.9.4'

branches:
  only:
  - master

env:
  global:
  - LOGS_DIR=/tmp/angular-material2-build/logs
  - SAUCE_USERNAME=angular-ci
  - BROWSER_STACK_USERNAME=angularteam1
  - BROWSER_PROVIDER_READY_FILE=/tmp/angular-material2-build/readyfile
  - BROWSER_PROVIDER_ERROR_FILE=/tmp/angular-material2-build/errorfile
  # Authentication variables SAUCE_ACCESS_KEY and BROWSER_STACK_ACCESS_KEY
  - secure: "CxxVeieX9E/ljO/3uAWG+/MdBBUanUSEwAPH+W0J5SXMRCbjqT+ckmjfjC3Le7mXCROKKVlhplKYo3v9kacx2/pmNUtYpxNYOVUyAXhTNuSjch+XEqQnhBxxcM0D2k+G9HG2WOtxwjUWBnu35512uy5k2ItZkZMGOFOia8IONdf5T/JPNGd4liFKtqfSEFRuJTFC+5+lSECWTQsUMYOfxVa2+LAquABtyIMv6HgTWla9Fyit/0Yhn2xHrbm6MtVOTWx9GWvqJyYqxNHd4Cl6LB/9+h7mL0gqdby63NmFCkbtCAHiufep9EXk8Ux6NcgOgDHg652XYRndpgHBB2jipU1XSLOEp0oOR3/3zHQuurvro6oR9BH3Q33+k/AM72YAXfF52JAW/BVoECVas1XV0KAHK6RbcrB98m9kKzoAYyHDq2G0tDxGK84o5bom+4HRder2F8t9NsjFmlZ+Kidlz2jdxM0XZHVpogQycY5CQwjQbzfXhvLaJbNO1qKf9vpKTZAR6U82nXQ+b6svn2e+V6AcHeRFB9jpSxLD4n7QBwDnO08FM498AZIXIz6TWrmAQcs6IwckJRnmeLCWiueeB5zigeJNFg8WdiGq+8dMOqOTPxv/SFoMOvlEDxtbt16snWNO7cdvzA46onZm6COiqJUQonPcZc5acimvUUR3g4M="
  - secure: "rdpDkWi2da7Q0MPwDM86eOeT6Uygu6f2frgqR0w0nqTZFiUds2dNUZPauJH8PVpqcRxanUw8H4QGoZ9XJxtNS7dw53bX5NhzCjcYkL5VlRSTHz5uCnrrgxoIQVky2YIblXVLtMKbL02aVNYVMLDgvrmcoQvAr1bWDZXi7+4mJMQpca67O94/RhUyCs1uRim63Fa+RLvhKJrocmWgAvxvG5o6TB7o4APkTbP5DMTdj5vFUWm/SJR6VQ60KF4U1OF1qFbOiMgmaCRQuwmQ70k9NswXpf/wqsFGxgq57ndNwpt5coWJRNT1o9zKyPfveWZtLcEAbTHMh3k1DC5qfaXkRvmJYVF1gT95xaDnOAJCnTP5ctbUDdgxfP4uqYI/eE4ShnrljolJh2n93ttiHpoUOiR3jfWKEsGfYtdu2VW1+guB9Kvucv4BWWZUMtejCffLPx4Y1mULdjKtJlHzZMyqVE/QMzVEm328bqagX/9V2jm5Z6dDYAS6OL2N5mxuA/gdrkbkjHbAauGQFlLkFN2golIrAw4QmT2nYXNNCCtQXn/ytXPdHHoxcUPHwtK2ljFKLFQ3QXlsprY+FN6k44MoITjQbuYWazyABtvfmKAnHgVJHPBkO0em3uFdBNOaCMJn76lLHghepSGKrhv0J2olPYbrJ/AWLnvT+LhZCXIr8Js="
  matrix:
    # Order: a slower build first, so that we don't occupy an idle travis worker waiting for others to complete.
    - MODE=lint
    - MODE=aot
    - MODE=payload
    - MODE=e2e
    - MODE=saucelabs_required
    - MODE=browserstack_required

matrix:
  fast_finish: true
  allow_failures:
  - env: "MODE=saucelabs_optional"
  - env: "MODE=browserstack_optional"

install:
  - npm install

before_script:
  - mkdir -p $LOGS_DIR

script:
  - ./scripts/ci/build-and-test.sh

after_success:
  - ./scripts/ci/after-success.sh

cache:
  directories:
    - node_modules
    - $HOME/.pub-cache
