# This workflow runs whenever the dev-app build workflow has completed. Deployment happens
# as part of a dedicated second workflow to avoid security issues where the building would
# otherwise occur in an authorized context where secrets could be leaked.
#
# More details can be found here:
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/.

name: Deploying dev-app to Firebase previews

on:
  workflow_run:
    workflows: ['Build dev-app for deployment']
    types: [completed]

permissions:
  # Needed in order to be able to comment on the pull request.
  pull-requests: write

jobs:
  deploy-dev-app:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.0.0
      - uses: angular/dev-infra/github-actions/deploy-previews/upload-artifacts-to-firebase@f41e98e0b6ac880bd589f928146c0b3b5827f0a2
        with:
          github-token: '${{secrets.GITHUB_TOKEN}}'
          workflow-artifact-name: 'dev-app'
          firebase-config-dir: './'
          firebase-public-dir: './dist/dev-app-web-pkg'
          firebase-project-id: 'ng-comp-dev'
          firebase-service-key: '${{secrets.FIREBASE_PREVIEW_SERVICE_TOKEN}}'
